import {
  normalizePathData, serializePathData, pathAnchors, pathControls,
  moveAnchor, moveControl, insertMidpoint, deleteAnchor, convertSegment, toggleClosed
} from './path-geometry.js';
import { combineMasks, traceMask, loopsToPath, connectedComponentsBySignature } from './boolean-utils.js';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const SVG_NS = 'http://www.w3.org/2000/svg';
const state = {
  nodeMode:false, nodePath:null, nodeSegments:[], nodeAnchor:-1, nodeModeType:'corner',
  snap:true, snapDrag:false, snapSuggestion:null, guides:[],
  shapeBuilder:null, paintSyncQueued:false
};
let toastTimer=null;

function toast(message) {
  const node=$('#toast'); if(!node) return; node.textContent=message; node.classList.add('visible');
  clearTimeout(toastTimer); toastTimer=setTimeout(()=>node.classList.remove('visible'),1900);
}
function status(message){ const n=$('#statusMessage'); if(n)n.textContent=message; }
function svg(){return $('#artboard svg');}
function cssEscape(value){return globalThis.CSS?.escape?CSS.escape(value):String(value).replace(/[^a-zA-Z0-9_-]/g,c=>`\\${c.codePointAt(0).toString(16)} `);}
function selectedNodes(){
  const root=svg(); if(!root)return[];
  return $$('#layersList .layer.selected').map(b=>b.dataset.id?root.querySelector(`[data-cw-id="${cssEscape(b.dataset.id)}"]`):null).filter(Boolean);
}
function primary(){const nodes=selectedNodes();return nodes.at(-1)||null;}
function serializeCurrent(){return svg()?new XMLSerializer().serializeToString(svg()):'';}
function commitSelectionChange(){
  const opacity=$('#opacityRange'); if(opacity&&selectedNodes().length) opacity.dispatchEvent(new Event('change',{bubbles:true}));
}
function applyViaSource(text, selectDomId=null){
  const editor=$('#sourceEditor'), apply=$('#applySourceBtn'); if(!editor||!apply)return;
  editor.value=text; editor.dispatchEvent(new Event('input',{bubbles:true})); apply.click();
  if(selectDomId) requestAnimationFrame(()=>{
    const n=svg()?.querySelector(`#${cssEscape(selectDomId)}`); if(!n)return;
    const layer=$(`#layersList .layer[data-id="${cssEscape(n.dataset.cwId||'')}"]`); layer?.click();
  });
}
function uniqueId(prefix){const root=svg();let id;do{id=`cw-${prefix}-${Math.random().toString(36).slice(2,9)}`;}while(root?.querySelector(`#${cssEscape(id)}`));return id;}
function ensureDefs(){
  const root=svg(); if(!root)return null; let defs=root.querySelector(':scope > defs');
  if(!defs){defs=document.createElementNS(SVG_NS,'defs');root.insertBefore(defs,root.firstChild);} return defs;
}
function clientToSvg(x,y){
  const root=svg(); if(!root)return{x:0,y:0}; const p=root.createSVGPoint();p.x=x;p.y=y;
  const m=root.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0};
}
function localPoint(node,x,y){
  const root=svg(); const p=root.createSVGPoint();p.x=x;p.y=y;const m=node.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0};
}
function screenPoint(node,x,y){
  const root=svg(); const p=root.createSVGPoint();p.x=x;p.y=y;const m=node.getScreenCTM();return m?p.matrixTransform(m):p;
}
function rootViewBox(){const root=svg();const v=root?.getAttribute('viewBox')?.trim().split(/[ ,]+/).map(Number);return v?.length===4?v:[0,0,960,600];}
function copyPresentation(from,to){
  ['fill','stroke','stroke-width','opacity','fill-rule','stroke-linecap','stroke-linejoin','vector-effect'].forEach(a=>{if(from.hasAttribute(a))to.setAttribute(a,from.getAttribute(a));});
  if(!to.hasAttribute('fill'))to.setAttribute('fill','#7257ff');
}

function injectUi(){
  const style=document.createElement('style'); style.textContent=`
  .cw-pro-panel{border-top:1px solid var(--border);padding:10px 0 2px;margin-top:10px}.cw-pro-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
  .cw-pro-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.cw-pro-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.cw-pro-grid .mini-button{height:30px;padding:0 7px;font-size:10px}.cw-pro-row{display:flex;gap:6px;align-items:center;margin:7px 0}.cw-pro-row>label{font-size:10px;color:var(--muted);min-width:50px}.cw-pro-row input[type=number],.cw-pro-row select{min-width:0;width:100%;background:var(--surface-2);border:1px solid var(--border);color:var(--text);border-radius:6px;padding:5px 6px;font-size:11px}
  .cw-node-overlay{position:absolute;inset:0;pointer-events:none;z-index:35}.cw-node-lines{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.cw-node-lines line{stroke:#6ee7f2;stroke-width:1;stroke-dasharray:3 2}.cw-node-handle{position:absolute;width:11px;height:11px;border-radius:50%;border:2px solid white;background:#7257ff;transform:translate(-50%,-50%);pointer-events:auto;cursor:move;box-shadow:0 0 0 2px rgba(114,87,255,.35)}.cw-node-handle.active{background:#ffbd59;width:13px;height:13px}.cw-control-handle{background:#10131a;border-color:#6ee7f2;width:9px;height:9px}
  .cw-ruler-top,.cw-ruler-left{position:absolute;z-index:30;background:color-mix(in srgb,var(--surface) 90%,transparent);border-color:var(--border);user-select:none}.cw-ruler-top{left:20px;right:0;top:0;height:20px;border-bottom:1px solid var(--border);background-image:repeating-linear-gradient(90deg,transparent 0 9px,var(--faint) 10px,transparent 11px 49px,var(--muted) 50px,transparent 51px)}.cw-ruler-left{top:20px;bottom:0;left:0;width:20px;border-right:1px solid var(--border);background-image:repeating-linear-gradient(180deg,transparent 0 9px,var(--faint) 10px,transparent 11px 49px,var(--muted) 50px,transparent 51px)}
  .cw-guide{position:absolute;z-index:29;pointer-events:auto}.cw-guide.v{top:20px;bottom:0;width:1px;border-left:1px dashed #2dd4bf;cursor:ew-resize}.cw-guide.h{left:20px;right:0;height:1px;border-top:1px dashed #2dd4bf;cursor:ns-resize}.cw-guide:hover{filter:drop-shadow(0 0 3px #2dd4bf)}
  .cw-snap-line{position:absolute;z-index:28;pointer-events:none;background:#f472b6}.cw-snap-line.v{width:1px;top:20px;bottom:0}.cw-snap-line.h{height:1px;left:20px;right:0}
  .cw-shape-overlay{position:absolute;z-index:40;pointer-events:none}.cw-shape-region{fill:rgba(114,87,255,.24);stroke:#a999ff;stroke-width:1.25;vector-effect:non-scaling-stroke;pointer-events:auto;cursor:pointer}.cw-shape-region.keep{fill:rgba(49,201,188,.42);stroke:#55eadf}.cw-shape-region:hover{fill:rgba(255,189,89,.4)}
  .cw-stop-row{display:grid;grid-template-columns:42px 1fr 42px 25px;gap:4px;align-items:center;margin:5px 0}.cw-stop-row input{min-width:0;width:100%}.cw-stop-row input[type=color]{height:26px;padding:1px}.cw-stop-row button{border:0;background:transparent;color:var(--muted);cursor:pointer}
  .cw-pro-badge{font-size:9px;padding:2px 5px;border-radius:99px;background:var(--accent-soft);color:#b9adff}.cw-tool-pro{color:#8fe8df!important}
  `; document.head.appendChild(style);
  const rail=$('.toolrail'); const hand=rail?.querySelector('[data-tool="hand"]');
  if(rail&&!$('#nodeTool')){const b=document.createElement('button');b.className='tool cw-tool-pro';b.id='nodeTool';b.title='Node / Bézier editor (N)';b.innerHTML='<span>◆</span><small>N</small>';rail.insertBefore(b,hand?.nextSibling||rail.firstChild);}
  const properties=$('#properties'); if(properties&&!$('#cwProStudio')){
    const section=document.createElement('section');section.id='cwProStudio';section.className='cw-pro-panel';section.innerHTML=`
      <div class="cw-pro-title"><strong>Pro Vector Studio</strong><span class="cw-pro-badge">SVG native</span></div>
      <details open><summary>Nodes & paths</summary><div class="cw-pro-grid three" style="margin-top:7px">
        <button class="mini-button" id="cwConvertPath">To Path</button><button class="mini-button" id="cwAddNode">+ Node</button><button class="mini-button" id="cwDeleteNode">− Node</button>
        <button class="mini-button" id="cwLineSeg">Line</button><button class="mini-button" id="cwCurveSeg">Curve</button><button class="mini-button" id="cwClosePath">Open/Close</button>
      </div><div class="cw-pro-row"><label>Node</label><select id="cwNodeMode"><option value="corner">Corner</option><option value="smooth">Smooth</option><option value="symmetric">Symmetric</option></select></div></details>
      <details><summary>Boolean & Shape Builder</summary><div class="cw-pro-grid" style="margin-top:7px">
        <button class="mini-button" data-cw-boolean="union">Union</button><button class="mini-button" data-cw-boolean="subtract">Subtract</button><button class="mini-button" data-cw-boolean="intersect">Intersect</button><button class="mini-button" data-cw-boolean="exclude">Exclude</button>
        <button class="mini-button" id="cwShapeBuilder">Shape Builder</button><button class="mini-button" id="cwApplyShapeBuilder" disabled>Apply regions</button>
      </div><div class="cw-pro-row"><label>Quality</label><select id="cwBooleanQuality"><option value="600">Fast</option><option value="950" selected>High</option><option value="1400">Ultra</option></select></div></details>
      <details><summary>Snap, guides & rulers</summary><div class="cw-pro-grid" style="margin-top:7px"><button class="mini-button" id="cwSnapToggle">Snap: On</button><button class="mini-button" id="cwClearGuides">Clear guides</button></div><div class="cw-pro-row"><label>Grid step</label><input id="cwSnapGrid" type="number" min="1" max="500" value="10"></div><small style="display:block;color:var(--muted);margin-top:6px">Snaps to object edges/centers, page, grid and guides. Click a ruler to add a guide; drag to reposition.</small></details>
      <details><summary>Paint & gradients</summary><div class="cw-pro-row"><label>Target</label><select id="cwPaintTarget"><option value="fill">Fill</option><option value="stroke">Stroke</option></select></div><div class="cw-pro-row"><label>Paint</label><select id="cwPaintType"><option value="solid">Solid</option><option value="linear">Linear gradient</option><option value="radial">Radial gradient</option><option value="none">None</option></select></div>
        <div class="cw-pro-row" id="cwSolidRow"><label>Color</label><input id="cwSolidColor" type="color" value="#7257ff"></div>
        <div id="cwGradientEditor" hidden><div class="cw-pro-row" id="cwLinearGeometry"><label>Angle</label><input id="cwGradientAngle" type="number" min="-360" max="360" value="0"></div><div id="cwRadialGeometry" hidden><div class="cw-pro-grid three"><label style="font-size:9px">CX %<input id="cwRadialCx" type="number" min="-100" max="200" value="50"></label><label style="font-size:9px">CY %<input id="cwRadialCy" type="number" min="-100" max="200" value="50"></label><label style="font-size:9px">R %<input id="cwRadialR" type="number" min="1" max="300" value="50"></label></div></div><div class="cw-pro-row"><label>Spread</label><select id="cwGradientSpread"><option value="pad">Pad</option><option value="reflect">Reflect</option><option value="repeat">Repeat</option></select></div><div id="cwGradientStops"></div><div class="cw-pro-grid"><button class="mini-button" id="cwAddStop">+ Stop</button><button class="mini-button" id="cwReverseStops">Reverse</button></div></div>
      </details>
      <details><summary>Masks & clipping</summary><div class="cw-pro-grid" style="margin-top:7px"><button class="mini-button" id="cwClipTop">Clip with top</button><button class="mini-button" id="cwMaskTop">Mask with top</button><button class="mini-button" id="cwMaskInvert">Invert mask</button><button class="mini-button" id="cwReleaseEffect">Release</button></div><small style="display:block;color:var(--muted);margin-top:6px">Select target object(s) plus the top clipping/mask shape.</small></details>
    `; properties.appendChild(section);
  }
  installRulers();
}

function activateNodeMode(force=null){const next=force==null?!state.nodeMode:force;state.nodeMode=next;$('#nodeTool')?.classList.toggle('active',next);if(next){document.querySelector('[data-tool="select"]')?.click();status('Node editor · select a path, drag anchors and Bézier handles');}else{removeNodeOverlay();status('Node editor closed');}syncNodeTarget();}
function syncNodeTarget(){if(!state.nodeMode)return;const node=primary();if(!node||node.tagName.toLowerCase()!=='path'){state.nodePath=null;removeNodeOverlay();status('Node editor · select a path or use “To Path”');return;}if(node!==state.nodePath){state.nodePath=node;state.nodeSegments=normalizePathData(node.getAttribute('d')||'');state.nodeAnchor=-1;}renderNodeOverlay();}
function removeNodeOverlay(){$('#cwNodeOverlay')?.remove();}
function nodeScreen(node,p){const q=screenPoint(node,p.x,p.y),wrap=$('#artboardWrap')?.getBoundingClientRect();return{x:q.x-wrap.left+$('#artboardWrap').scrollLeft,y:q.y-wrap.top+$('#artboardWrap').scrollTop};}
function addLine(svgEl,a,b){const l=document.createElementNS(SVG_NS,'line');l.setAttribute('x1',a.x);l.setAttribute('y1',a.y);l.setAttribute('x2',b.x);l.setAttribute('y2',b.y);svgEl.appendChild(l);}
function renderNodeOverlay(){removeNodeOverlay();const node=state.nodePath;if(!node?.isConnected)return;const wrap=$('#artboardWrap');if(!wrap)return;const overlay=document.createElement('div');overlay.id='cwNodeOverlay';overlay.className='cw-node-overlay';const lines=document.createElementNS(SVG_NS,'svg');lines.classList.add('cw-node-lines');overlay.appendChild(lines);const anchors=pathAnchors(state.nodeSegments),controls=pathControls(state.nodeSegments);controls.forEach(c=>{const cp=nodeScreen(node,c);let anchor=null;if(c.slot==='c1'||c.slot==='q'){const prev=state.nodeSegments[c.index-1];if(prev&&'x'in prev)anchor=nodeScreen(node,prev);}else{const seg=state.nodeSegments[c.index];anchor=nodeScreen(node,seg);}if(anchor)addLine(lines,anchor,cp);const h=document.createElement('button');h.className='cw-node-handle cw-control-handle';h.style.left=`${cp.x}px`;h.style.top=`${cp.y}px`;h.title='Bézier control handle';h.addEventListener('pointerdown',e=>startControlDrag(e,c));overlay.appendChild(h);});anchors.forEach(a=>{const p=nodeScreen(node,a);const h=document.createElement('button');h.className=`cw-node-handle${a.index===state.nodeAnchor?' active':''}`;h.style.left=`${p.x}px`;h.style.top=`${p.y}px`;h.title=`${a.cmd} node ${a.index}`;h.addEventListener('click',e=>{e.stopPropagation();state.nodeAnchor=a.index;renderNodeOverlay();});h.addEventListener('pointerdown',e=>startAnchorDrag(e,a));overlay.appendChild(h);});wrap.appendChild(overlay);}
function writeNodePath(){if(state.nodePath)state.nodePath.setAttribute('d',serializePathData(state.nodeSegments));}
function startAnchorDrag(event,a){event.preventDefault();event.stopPropagation();state.nodeAnchor=a.index;const move=e=>{const p=localPoint(state.nodePath,e.clientX,e.clientY);state.nodeSegments=moveAnchor(state.nodeSegments,a.index,p.x,p.y);writeNodePath();renderNodeOverlay();};const up=()=>{window.removeEventListener('pointermove',move);commitSelectionChange();renderNodeOverlay();};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function startControlDrag(event,c){event.preventDefault();event.stopPropagation();state.nodeAnchor=c.index;const move=e=>{const p=localPoint(state.nodePath,e.clientX,e.clientY);state.nodeSegments=moveControl(state.nodeSegments,c.index,c.slot,p.x,p.y,state.nodeModeType);writeNodePath();renderNodeOverlay();};const up=()=>{window.removeEventListener('pointermove',move);commitSelectionChange();renderNodeOverlay();};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});}
function shapeToPath(node){if(!node)return null;const tag=node.tagName.toLowerCase();let d='';const n=a=>parseFloat(node.getAttribute(a))||0;if(tag==='rect'){const x=n('x'),y=n('y'),w=n('width'),h=n('height');d=`M${x} ${y} L${x+w} ${y} L${x+w} ${y+h} L${x} ${y+h} Z`;}else if(tag==='circle'){const cx=n('cx'),cy=n('cy'),r=n('r'),k=.5522847498*r;d=`M${cx+r} ${cy} C${cx+r} ${cy+k} ${cx+k} ${cy+r} ${cx} ${cy+r} C${cx-k} ${cy+r} ${cx-r} ${cy+k} ${cx-r} ${cy} C${cx-r} ${cy-k} ${cx-k} ${cy-r} ${cx} ${cy-r} C${cx+k} ${cy-r} ${cx+r} ${cy-k} ${cx+r} ${cy} Z`;}else if(tag==='ellipse'){const cx=n('cx'),cy=n('cy'),rx=n('rx'),ry=n('ry'),kx=.5522847498*rx,ky=.5522847498*ry;d=`M${cx+rx} ${cy} C${cx+rx} ${cy+ky} ${cx+kx} ${cy+ry} ${cx} ${cy+ry} C${cx-kx} ${cy+ry} ${cx-rx} ${cy+ky} ${cx-rx} ${cy} C${cx-rx} ${cy-ky} ${cx-kx} ${cy-ry} ${cx} ${cy-ry} C${cx+kx} ${cy-ry} ${cx+rx} ${cy-ky} ${cx+rx} ${cy} Z`;}else if(tag==='line')d=`M${n('x1')} ${n('y1')} L${n('x2')} ${n('y2')}`;else if(tag==='polyline'||tag==='polygon'){const pts=(node.getAttribute('points')||'').trim().split(/[ ,]+/).map(Number);for(let i=0;i+1<pts.length;i+=2)d+=`${i?'L':'M'}${pts[i]} ${pts[i+1]} `;if(tag==='polygon')d+='Z';}else if(tag==='path')return node;else return null;const path=document.createElementNS(SVG_NS,'path');path.setAttribute('d',d.trim());[...node.attributes].forEach(a=>{if(!['x','y','width','height','rx','ry','cx','cy','r','x1','y1','x2','y2','points'].includes(a.name))path.setAttribute(a.name,a.value);});const id=node.id||uniqueId('path');path.id=id;node.replaceWith(path);applyViaSource(serializeCurrent(),id);toast('Converted to editable path');return path;}
function selectedSegmentIndex(){return state.nodeAnchor>0?state.nodeAnchor:(state.nodeSegments.length>1?1:-1);}
function nodeCommand(action){if(action==='convert'){shapeToPath(primary());return;}syncNodeTarget();if(!state.nodePath)return toast('Select a path first');const i=selectedSegmentIndex();if(action==='add'&&i>0)state.nodeSegments=insertMidpoint(state.nodeSegments,i);if(action==='delete'&&state.nodeAnchor>0)state.nodeSegments=deleteAnchor(state.nodeSegments,state.nodeAnchor);if(action==='line'&&i>0)state.nodeSegments=convertSegment(state.nodeSegments,i,'line');if(action==='curve'&&i>0)state.nodeSegments=convertSegment(state.nodeSegments,i,'curve');if(action==='close')state.nodeSegments=toggleClosed(state.nodeSegments);state.nodeAnchor=-1;writeNodePath();commitSelectionChange();renderNodeOverlay();}

function whitenClone(node){const c=node.cloneNode(true);[c,...c.querySelectorAll('*')].forEach(n=>{n.setAttribute?.('fill','#fff');n.setAttribute?.('fill-opacity','1');n.setAttribute?.('stroke','none');n.removeAttribute?.('opacity');n.removeAttribute?.('filter');});return c;}
async function nodeMask(node, dims){const root=svg(),[vx,vy,vw,vh]=rootViewBox(),defs=root.querySelector(':scope > defs')?.cloneNode(true);const wrapper=document.createElementNS(SVG_NS,'svg');wrapper.setAttribute('xmlns',SVG_NS);wrapper.setAttribute('viewBox',`${vx} ${vy} ${vw} ${vh}`);wrapper.setAttribute('width',dims.w);wrapper.setAttribute('height',dims.h);if(defs)wrapper.appendChild(defs);const clone=whitenClone(node),holder=document.createElementNS(SVG_NS,'g');const rootScreen=root.getScreenCTM(),nodeScreen=node.getScreenCTM();if(rootScreen&&nodeScreen){const m=rootScreen.inverse().multiply(nodeScreen);holder.setAttribute('transform',`matrix(${m.a} ${m.b} ${m.c} ${m.d} ${m.e} ${m.f})`);clone.removeAttribute('transform');}holder.appendChild(clone);wrapper.appendChild(holder);const blob=new Blob([new XMLSerializer().serializeToString(wrapper)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob);try{const image=new Image();await new Promise((res,rej)=>{image.onload=res;image.onerror=rej;image.src=url;});const canvas=document.createElement('canvas');canvas.width=dims.w;canvas.height=dims.h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.clearRect(0,0,dims.w,dims.h);ctx.drawImage(image,0,0,dims.w,dims.h);const data=ctx.getImageData(0,0,dims.w,dims.h).data,mask=new Uint8Array(dims.w*dims.h);for(let i=0,j=0;i<data.length;i+=4,j++)mask[j]=data[i+3]>24?1:0;return mask;}finally{URL.revokeObjectURL(url);}}
function rasterDims(){const [, ,w,h]=rootViewBox(),quality=Number($('#cwBooleanQuality')?.value)||950,scale=quality/Math.max(w,h);return{w:Math.max(8,Math.round(w*scale)),h:Math.max(8,Math.round(h*scale))};}
async function rasterMasks(nodes){const dims=rasterDims(),masks=[];status(`Vector boolean · rasterizing ${nodes.length} shapes at ${dims.w}×${dims.h}…`);for(const node of nodes)masks.push(await nodeMask(node,dims));return{masks,dims};}
function outputPathFromMask(mask,dims){const loops=traceMask(mask,dims.w,dims.h),[vx,vy,vw,vh]=rootViewBox();return loopsToPath(loops,{originX:vx,originY:vy,scaleX:vw/dims.w,scaleY:vh/dims.h,precision:2});}
function replaceSelectionWithPath(d,sourceNode,label='Boolean result'){if(!d)return toast('Operation produced no filled region');const nodes=selectedNodes();if(!nodes.length)return;const root=svg(),parent=nodes.every(n=>n.parentNode===nodes[0].parentNode)?nodes[0].parentNode:root;const path=document.createElementNS(SVG_NS,'path');path.id=uniqueId('boolean');path.setAttribute('d',d);path.setAttribute('fill-rule','evenodd');copyPresentation(sourceNode||nodes[0],path);if(path.getAttribute('fill')==='none')path.setAttribute('fill','#7257ff');path.setAttribute('stroke','none');parent.insertBefore(path,nodes[0]);nodes.forEach(n=>n.remove());applyViaSource(serializeCurrent(),path.id);toast(label);status(`${label} · editable SVG path created`);}
async function booleanOperation(operation){const nodes=selectedNodes().filter(n=>n.dataset.cwConnector!=='true');if(nodes.length<2)return toast('Select at least two filled shapes');try{const {masks,dims}=await rasterMasks(nodes);const result=combineMasks(masks,operation);replaceSelectionWithPath(outputPathFromMask(result,dims),nodes[0],`${operation[0].toUpperCase()+operation.slice(1)} complete`);}catch(e){console.error(e);toast('Boolean operation failed for this selection');}}
function removeShapeBuilder(){state.shapeBuilder?.overlay?.remove();state.shapeBuilder=null;const b=$('#cwApplyShapeBuilder');if(b)b.disabled=true;}
async function startShapeBuilder(){removeShapeBuilder();const nodes=selectedNodes().filter(n=>n.dataset.cwConnector!=='true');if(nodes.length<2)return toast('Select two or more shapes');if(nodes.length>12)return toast('Shape Builder supports up to 12 selected shapes per pass');try{const {masks,dims}=await rasterMasks(nodes),regions=connectedComponentsBySignature(masks,dims.w,dims.h);if(!regions.length)return toast('No filled regions found');const root=svg(),rect=root.getBoundingClientRect(),wrap=$('#artboardWrap'),wr=wrap.getBoundingClientRect(),overlay=document.createElementNS(SVG_NS,'svg');overlay.classList.add('cw-shape-overlay');overlay.style.left=`${rect.left-wr.left+wrap.scrollLeft}px`;overlay.style.top=`${rect.top-wr.top+wrap.scrollTop}px`;overlay.style.width=`${rect.width}px`;overlay.style.height=`${rect.height}px`;overlay.setAttribute('viewBox',root.getAttribute('viewBox'));overlay.style.pointerEvents='none';const [vx,vy,vw,vh]=rootViewBox();regions.forEach((region,index)=>{const d=loopsToPath(region.loops,{originX:vx,originY:vy,scaleX:vw/dims.w,scaleY:vh/dims.h,precision:2});const p=document.createElementNS(SVG_NS,'path');p.setAttribute('d',d);p.setAttribute('class','cw-shape-region keep');p.dataset.index=index;p.style.pointerEvents='auto';p.addEventListener('click',e=>{e.stopPropagation();p.classList.toggle('keep');region.keep=p.classList.contains('keep');});region.keep=true;overlay.appendChild(p);});wrap.appendChild(overlay);state.shapeBuilder={overlay,regions,dims,nodes,source:nodes[0]};$('#cwApplyShapeBuilder').disabled=false;status(`Shape Builder · click ${regions.length} detected regions to keep/remove, then Apply`);toast(`${regions.length} editable regions detected`);}catch(e){console.error(e);toast('Shape Builder could not analyze this selection');}}
function applyShapeBuilder(){const sb=state.shapeBuilder;if(!sb)return;const [vx,vy,vw,vh]=rootViewBox();const loops=sb.regions.filter(r=>r.keep).flatMap(r=>r.loops);const d=loopsToPath(loops,{originX:vx,originY:vy,scaleX:vw/sb.dims.w,scaleY:vh/sb.dims.h,precision:2});removeShapeBuilder();replaceSelectionWithPath(d,sb.source,'Shape Builder applied');}

function installRulers(){const area=$('#canvasArea');if(!area||$('#cwRulerTop'))return;area.style.position='relative';const top=document.createElement('div');top.id='cwRulerTop';top.className='cw-ruler-top';top.title='Click to add vertical guide';const left=document.createElement('div');left.id='cwRulerLeft';left.className='cw-ruler-left';left.title='Click to add horizontal guide';area.append(top,left);top.addEventListener('pointerdown',e=>addGuideFromClient('v',e.clientX,e.clientY));left.addEventListener('pointerdown',e=>addGuideFromClient('h',e.clientX,e.clientY));window.addEventListener('resize',renderGuides);area.addEventListener('scroll',renderGuides,{passive:true});}
function addGuideFromClient(dir,x,y){const p=clientToSvg(x,y);state.guides.push({dir,value:dir==='v'?p.x:p.y});renderGuides();toast(`${dir==='v'?'Vertical':'Horizontal'} guide added`);}
function guideScreen(g){const root=svg(),p=root.createSVGPoint(),[vx,vy]=rootViewBox();p.x=g.dir==='v'?g.value:vx;p.y=g.dir==='h'?g.value:vy;const q=p.matrixTransform(root.getScreenCTM()),area=$('#canvasArea').getBoundingClientRect();return g.dir==='v'?q.x-area.left+$('#canvasArea').scrollLeft:q.y-area.top+$('#canvasArea').scrollTop;}
function renderGuides(){const area=$('#canvasArea');if(!area)return;$$('.cw-guide').forEach(n=>n.remove());state.guides.forEach((g,index)=>{const line=document.createElement('div');line.className=`cw-guide ${g.dir}`;const pos=guideScreen(g);if(g.dir==='v')line.style.left=`${pos}px`;else line.style.top=`${pos}px`;line.title='Drag guide · double-click to remove';line.addEventListener('dblclick',()=>{state.guides.splice(index,1);renderGuides();});line.addEventListener('pointerdown',e=>{e.stopPropagation();const move=ev=>{const p=clientToSvg(ev.clientX,ev.clientY);g.value=g.dir==='v'?p.x:p.y;renderGuides();};const up=()=>window.removeEventListener('pointermove',move);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});});area.appendChild(line);});}
function selectedRect(){const nodes=selectedNodes();if(!nodes.length)return null;const rects=nodes.map(n=>n.getBoundingClientRect()).filter(r=>r.width||r.height);if(!rects.length)return null;return{left:Math.min(...rects.map(r=>r.left)),right:Math.max(...rects.map(r=>r.right)),top:Math.min(...rects.map(r=>r.top)),bottom:Math.max(...rects.map(r=>r.bottom))};}
function snapCandidates(){const root=svg(),selected=new Set(selectedNodes()),xs=[],ys=[];const rr=root.getBoundingClientRect();xs.push(rr.left,(rr.left+rr.right)/2,rr.right);ys.push(rr.top,(rr.top+rr.bottom)/2,rr.bottom);root.querySelectorAll('[data-cw-id]').forEach(n=>{if(selected.has(n)||n.dataset.cwConnector==='true'||n.getAttribute('display')==='none')return;const r=n.getBoundingClientRect();if(!r.width&&!r.height)return;xs.push(r.left,(r.left+r.right)/2,r.right);ys.push(r.top,(r.top+r.bottom)/2,r.bottom);});state.guides.forEach(g=>{const root=svg(),p=root.createSVGPoint(),[vx,vy]=rootViewBox();p.x=g.dir==='v'?g.value:vx;p.y=g.dir==='h'?g.value:vy;const q=p.matrixTransform(root.getScreenCTM());(g.dir==='v'?xs:ys).push(g.dir==='v'?q.x:q.y);});const step=Math.max(1,Number($('#cwSnapGrid')?.value)||10),[vx,vy,vw,vh]=rootViewBox(),matrix=root.getScreenCTM();if(matrix){const p=root.createSVGPoint();for(let x=Math.ceil(vx/step)*step;x<=vx+vw;x+=step){p.x=x;p.y=vy;xs.push(p.matrixTransform(matrix).x);}for(let y=Math.ceil(vy/step)*step;y<=vy+vh;y+=step){p.x=vx;p.y=y;ys.push(p.matrixTransform(matrix).y);}}return{xs,ys};}
function computeSnap(){if(!state.snap)return null;const r=selectedRect();if(!r)return null;const ownX=[r.left,(r.left+r.right)/2,r.right],ownY=[r.top,(r.top+r.bottom)/2,r.bottom],{xs,ys}=snapCandidates(),threshold=7;let bestX=null,bestY=null;ownX.forEach(a=>xs.forEach(b=>{const d=b-a;if(Math.abs(d)<=threshold&&(!bestX||Math.abs(d)<Math.abs(bestX.d)))bestX={d,line:b};}));ownY.forEach(a=>ys.forEach(b=>{const d=b-a;if(Math.abs(d)<=threshold&&(!bestY||Math.abs(d)<Math.abs(bestY.d)))bestY={d,line:b};}));return{dx:bestX?.d||0,dy:bestY?.d||0,xLine:bestX?.line,yLine:bestY?.line};}
function showSnap(s){$$('.cw-snap-line').forEach(n=>n.remove());const area=$('#canvasArea');if(!area||!s)return;const ar=area.getBoundingClientRect();if(s.xLine!=null){const l=document.createElement('div');l.className='cw-snap-line v';l.style.left=`${s.xLine-ar.left+area.scrollLeft}px`;area.appendChild(l);}if(s.yLine!=null){const l=document.createElement('div');l.className='cw-snap-line h';l.style.top=`${s.yLine-ar.top+area.scrollTop}px`;area.appendChild(l);}}
function translateSelectedScreen(dx,dy){if(!dx&&!dy)return;const root=svg(),m=root.getScreenCTM();if(!m)return;const p0=root.createSVGPoint(),p1=root.createSVGPoint();p0.x=0;p0.y=0;p1.x=dx;p1.y=dy;const a=p0.matrixTransform(m.inverse()),b=p1.matrixTransform(m.inverse()),sx=b.x-a.x,sy=b.y-a.y;selectedNodes().filter(n=>n.dataset.cwConnector!=='true').forEach(n=>{const t=n.getAttribute('transform')||'';n.setAttribute('transform',`translate(${sx} ${sy}) ${t}`.trim());});commitSelectionChange();}
function bindSnapping(){$('#artboard')?.addEventListener('pointerdown',e=>{if(e.button===0&&!state.nodeMode&&e.target.closest?.('[data-cw-id]'))state.snapDrag=true;},true);window.addEventListener('pointermove',()=>{if(!state.snapDrag)return;state.snapSuggestion=computeSnap();showSnap(state.snapSuggestion);});window.addEventListener('pointerup',()=>{if(!state.snapDrag)return;state.snapDrag=false;const s=state.snapSuggestion;state.snapSuggestion=null;showSnap(null);if(s&&(s.dx||s.dy)){translateSelectedScreen(s.dx,s.dy);toast('Snapped to alignment');}});}

function paintTarget(){return $('#cwPaintTarget')?.value||'fill';}
function refId(value){return String(value||'').match(/^url\(#(.+)\)$/)?.[1]||null;}
function selectedGradient(){const n=primary(),root=svg();if(!n||!root)return null;const id=refId(n.getAttribute(paintTarget()));return id?root.querySelector(`#${cssEscape(id)}`):null;}
function syncPaint(){if(state.paintSyncQueued)return;state.paintSyncQueued=true;requestAnimationFrame(()=>{state.paintSyncQueued=false;const n=primary();if(!n)return;const attr=paintTarget(),value=n.getAttribute(attr)||'none',g=selectedGradient(),type=g?.tagName.toLowerCase()==='lineargradient'?'linear':g?.tagName.toLowerCase()==='radialgradient'?'radial':value==='none'?'none':'solid';$('#cwPaintType').value=type;$('#cwSolidRow').hidden=type!=='solid';$('#cwGradientEditor').hidden=!['linear','radial'].includes(type);if(type==='solid'&&/^#[0-9a-f]{6}$/i.test(value))$('#cwSolidColor').value=value;if(g){$('#cwGradientSpread').value=g.getAttribute('spreadMethod')||'pad';$('#cwLinearGeometry').hidden=type!=='linear';$('#cwRadialGeometry').hidden=type!=='radial';if(type==='linear')$('#cwGradientAngle').value=String(Math.round(gradientAngle(g)));if(type==='radial'){const pct=v=>Math.round((parseFloat(v)||.5)*(String(v||'').includes('%')?1:100));$('#cwRadialCx').value=pct(g.getAttribute('cx')||'.5');$('#cwRadialCy').value=pct(g.getAttribute('cy')||'.5');$('#cwRadialR').value=pct(g.getAttribute('r')||'.5');}renderStops(g);}});}
function gradientAngle(g){const x1=parseFloat(g.getAttribute('x1'))||0,y1=parseFloat(g.getAttribute('y1'))||0,x2=parseFloat(g.getAttribute('x2'))||1,y2=parseFloat(g.getAttribute('y2'))||0;return Math.atan2(y2-y1,x2-x1)*180/Math.PI;}
function setGradientAngle(g,deg){const a=deg*Math.PI/180,c=Math.cos(a)*.5,s=Math.sin(a)*.5;g.setAttribute('x1',.5-c);g.setAttribute('y1',.5-s);g.setAttribute('x2',.5+c);g.setAttribute('y2',.5+s);}
function makeGradient(type){const defs=ensureDefs(),g=document.createElementNS(SVG_NS,type==='linear'?'linearGradient':'radialGradient');g.id=uniqueId(type==='linear'?'linear':'radial');g.setAttribute('gradientUnits','objectBoundingBox');if(type==='linear')setGradientAngle(g,0);else{g.setAttribute('cx','.5');g.setAttribute('cy','.5');g.setAttribute('r','.5');}[['0%','#7257ff'],['100%','#31c9bc']].forEach(([o,c])=>{const s=document.createElementNS(SVG_NS,'stop');s.setAttribute('offset',o);s.setAttribute('stop-color',c);g.appendChild(s);});defs.appendChild(g);return g;}
function applyPaintType(type){const n=primary();if(!n)return toast('Select an object');const attr=paintTarget();if(type==='none')n.setAttribute(attr,'none');else if(type==='solid')n.setAttribute(attr,$('#cwSolidColor').value);else{let g=selectedGradient();if(!g||g.tagName.toLowerCase()!==(type==='linear'?'lineargradient':'radialgradient'))g=makeGradient(type);n.setAttribute(attr,`url(#${g.id})`);}commitSelectionChange();syncPaint();}
function renderStops(g){const box=$('#cwGradientStops');if(!box)return;box.replaceChildren();[...g.querySelectorAll(':scope > stop')].forEach((stop,index)=>{const row=document.createElement('div');row.className='cw-stop-row';const color=stop.getAttribute('stop-color')||'#000000',raw=stop.getAttribute('offset')||'0',offset=Math.round(parseFloat(raw)*(raw.includes('%')?1:100)),opacity=Math.round((Number.isFinite(parseFloat(stop.getAttribute('stop-opacity')))?parseFloat(stop.getAttribute('stop-opacity')):1)*100);row.innerHTML=`<input type="color" value="${/^#[0-9a-f]{6}$/i.test(color)?color:'#000000'}" title="Stop color"><input type="range" min="0" max="100" value="${offset}" title="Offset"><input type="number" min="0" max="100" value="${opacity}" title="Opacity"><button title="Remove stop">×</button>`;const inputs=row.querySelectorAll('input');inputs[0].addEventListener('input',e=>stop.setAttribute('stop-color',e.target.value));inputs[1].addEventListener('input',e=>stop.setAttribute('offset',`${e.target.value}%`));inputs[2].addEventListener('input',e=>stop.setAttribute('stop-opacity',String(Number(e.target.value)/100)));inputs.forEach(i=>i.addEventListener('change',()=>commitSelectionChange()));row.querySelector('button').addEventListener('click',()=>{if(g.querySelectorAll('stop').length<=2)return toast('A gradient needs at least two stops');stop.remove();commitSelectionChange();renderStops(g);});box.appendChild(row);});}
function stopPercent(stop){const raw=stop?.getAttribute('offset')||'0';return parseFloat(raw)*(raw.includes('%')?1:100);}
function addStop(){const g=selectedGradient();if(!g)return;const stops=[...g.querySelectorAll('stop')],last=stops.at(-1),before=stops.at(-2),offset=(stopPercent(before)+stopPercent(last))/2;const s=document.createElementNS(SVG_NS,'stop');s.setAttribute('offset',`${Math.max(0,Math.min(100,offset))}%`);s.setAttribute('stop-color','#ffffff');g.insertBefore(s,last);commitSelectionChange();renderStops(g);}
function reverseStops(){const g=selectedGradient();if(!g)return;const stops=[...g.querySelectorAll('stop')];stops.forEach(s=>s.setAttribute('offset',`${100-stopPercent(s)}%`));stops.reverse().forEach(s=>g.appendChild(s));commitSelectionChange();renderStops(g);}

function documentOrder(nodes){const all=[...svg().querySelectorAll('*')];return nodes.slice().sort((a,b)=>all.indexOf(a)-all.indexOf(b));}
function effectRef(node,kind){return refId(node?.getAttribute(kind));}
function makeEffect(kind,invert=false){const nodes=documentOrder(selectedNodes().filter(n=>n.dataset.cwConnector!=='true'));if(nodes.length<2)return toast('Select target object(s) and a top shape');const source=nodes.at(-1),targets=nodes.slice(0,-1);if(!targets.every(n=>n.parentNode===targets[0].parentNode&&source.parentNode===targets[0].parentNode))return toast('For clip/mask, select objects in the same group/layer');const parent=source.parentNode,defs=ensureDefs(),id=uniqueId(kind==='clip-path'?'clip':'mask');let def;if(kind==='clip-path'){def=document.createElementNS(SVG_NS,'clipPath');def.id=id;def.appendChild(source.cloneNode(true));}else{def=document.createElementNS(SVG_NS,'mask');def.id=id;const [vx,vy,vw,vh]=rootViewBox();def.setAttribute('maskUnits','userSpaceOnUse');const originalHolder=document.createElementNS(SVG_NS,'g');originalHolder.setAttribute('display','none');originalHolder.appendChild(source.cloneNode(true));def.appendChild(originalHolder);if(invert){const bg=document.createElementNS(SVG_NS,'rect');bg.setAttribute('x',vx);bg.setAttribute('y',vy);bg.setAttribute('width',vw);bg.setAttribute('height',vh);bg.setAttribute('fill','#fff');def.appendChild(bg);}const clone=source.cloneNode(true);[clone,...clone.querySelectorAll('*')].forEach(n=>{n.setAttribute?.('fill',invert?'#000':'#fff');n.setAttribute?.('stroke','none');n.setAttribute?.('opacity','1');});def.appendChild(clone);}defs.appendChild(def);const group=document.createElementNS(SVG_NS,'g');group.id=uniqueId('effect');parent.insertBefore(group,targets[0]);targets.forEach(n=>group.appendChild(n));group.setAttribute(kind,`url(#${id})`);source.remove();applyViaSource(serializeCurrent(),group.id);toast(kind==='clip-path'?'Clip path applied':invert?'Inverted mask applied':'Mask applied');}
function releaseEffect(){const n=primary();if(!n)return;const kind=n.hasAttribute('clip-path')?'clip-path':n.hasAttribute('mask')?'mask':null;if(!kind)return toast('Select an object/group with a clip or mask');const id=effectRef(n,kind),def=id?svg().querySelector(`#${cssEscape(id)}`):null;let source=null;if(def){if(kind==='mask'&&def.firstElementChild?.getAttribute('display')==='none')source=def.firstElementChild.firstElementChild?.cloneNode(true);else source=def.firstElementChild?.cloneNode(true);}n.removeAttribute(kind);if(source){source.removeAttribute('data-cw-id');n.parentNode.insertBefore(source,n.nextSibling);}def?.remove();commitSelectionChange();toast('Clip/mask released');}

function bindUi(){
  $('#nodeTool')?.addEventListener('click',()=>activateNodeMode());
  $('#cwConvertPath')?.addEventListener('click',()=>nodeCommand('convert'));$('#cwAddNode')?.addEventListener('click',()=>nodeCommand('add'));$('#cwDeleteNode')?.addEventListener('click',()=>nodeCommand('delete'));$('#cwLineSeg')?.addEventListener('click',()=>nodeCommand('line'));$('#cwCurveSeg')?.addEventListener('click',()=>nodeCommand('curve'));$('#cwClosePath')?.addEventListener('click',()=>nodeCommand('close'));$('#cwNodeMode')?.addEventListener('change',e=>state.nodeModeType=e.target.value);
  $$('[data-cw-boolean]').forEach(b=>b.addEventListener('click',()=>booleanOperation(b.dataset.cwBoolean)));$('#cwShapeBuilder')?.addEventListener('click',startShapeBuilder);$('#cwApplyShapeBuilder')?.addEventListener('click',applyShapeBuilder);
  $('#cwSnapToggle')?.addEventListener('click',e=>{state.snap=!state.snap;e.currentTarget.textContent=`Snap: ${state.snap?'On':'Off'}`;toast(`Smart snapping ${state.snap?'enabled':'disabled'}`);});$('#cwClearGuides')?.addEventListener('click',()=>{state.guides=[];renderGuides();toast('Guides cleared');});
  $('#cwPaintTarget')?.addEventListener('change',syncPaint);$('#cwPaintType')?.addEventListener('change',e=>applyPaintType(e.target.value));$('#cwSolidColor')?.addEventListener('input',e=>{const n=primary();if(n&&$('#cwPaintType').value==='solid')n.setAttribute(paintTarget(),e.target.value);});$('#cwSolidColor')?.addEventListener('change',commitSelectionChange);$('#cwGradientAngle')?.addEventListener('change',e=>{const g=selectedGradient();if(g?.tagName.toLowerCase()==='lineargradient'){setGradientAngle(g,Number(e.target.value)||0);commitSelectionChange();}});[['cwRadialCx','cx'],['cwRadialCy','cy'],['cwRadialR','r']].forEach(([id,attr])=>$('#'+id)?.addEventListener('change',e=>{const g=selectedGradient();if(g?.tagName.toLowerCase()==='radialgradient'){g.setAttribute(attr,`${Number(e.target.value)||50}%`);commitSelectionChange();}}));$('#cwGradientSpread')?.addEventListener('change',e=>{const g=selectedGradient();if(g){g.setAttribute('spreadMethod',e.target.value);commitSelectionChange();}});$('#cwAddStop')?.addEventListener('click',addStop);$('#cwReverseStops')?.addEventListener('click',reverseStops);
  $('#cwClipTop')?.addEventListener('click',()=>makeEffect('clip-path'));$('#cwMaskTop')?.addEventListener('click',()=>makeEffect('mask'));$('#cwMaskInvert')?.addEventListener('click',()=>makeEffect('mask',true));$('#cwReleaseEffect')?.addEventListener('click',releaseEffect);
  $('#layersList')?.addEventListener('click',()=>{requestAnimationFrame(()=>{syncNodeTarget();syncPaint();});});
  new MutationObserver(()=>{syncNodeTarget();syncPaint();renderGuides();}).observe($('#artboard'),{childList:true,subtree:true});
  window.addEventListener('keydown',e=>{if(/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName))return;if(e.key.toLowerCase()==='n'){e.preventDefault();activateNodeMode();}if(e.key==='Escape'){removeShapeBuilder();if(state.nodeMode)activateNodeMode(false);}});
  bindSnapping();
}

injectUi();bindUi();syncPaint();
